[2024-03-10T20:29:51.867+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_category_consommation scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-10T20:29:52.516+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_category_consommation scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-10T20:29:52.636+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-03-10T20:29:53.123+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_dim_category_consommation> on 2024-03-08 00:00:00+00:00
[2024-03-10T20:29:53.245+0000] {standard_task_runner.py:57} INFO - Started process 1737 to run task
[2024-03-10T20:29:53.395+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_dim_category_consommation', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '888', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmp2rhqk1x_']
[2024-03-10T20:29:53.447+0000] {standard_task_runner.py:85} INFO - Job 888: Subtask create_dim_category_consommation
[2024-03-10T20:29:53.924+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_dim_category_consommation scheduled__2024-03-08T00:00:00+00:00 [running]> on host 952b3f8a1a94
[2024-03-10T20:29:54.777+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_dim_category_consommation' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2024-03-10T20:29:54.965+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 253, in create_dim_category_consommation
    category_consommation_dim = df_conso_energy_region[['code_categorie_consommation',  'libelle_categorie_consommation']].drop_duplicates().reset_index(drop=True)
TypeError: 'NoneType' object is not subscriptable
[2024-03-10T20:29:55.095+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=EnergyWarehouse, task_id=create_dim_category_consommation, execution_date=20240308T000000, start_date=20240310T202951, end_date=20240310T202955
[2024-03-10T20:29:56.681+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 888 for task create_dim_category_consommation ('NoneType' object is not subscriptable; 1737)
[2024-03-10T20:29:56.857+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-10T20:29:57.315+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
