[2024-03-10T21:10:51.984+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_fact_table_conso_energy_region manual__2024-03-10T21:03:03.293033+00:00 [queued]>
[2024-03-10T21:10:52.023+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_fact_table_conso_energy_region manual__2024-03-10T21:03:03.293033+00:00 [queued]>
[2024-03-10T21:10:52.027+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-03-10T21:10:52.092+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_fact_table_conso_energy_region> on 2024-03-10 21:03:03.293033+00:00
[2024-03-10T21:10:52.114+0000] {standard_task_runner.py:57} INFO - Started process 2995 to run task
[2024-03-10T21:10:52.147+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_fact_table_conso_energy_region', 'manual__2024-03-10T21:03:03.293033+00:00', '--job-id', '1005', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmpahky0c68']
[2024-03-10T21:10:52.159+0000] {standard_task_runner.py:85} INFO - Job 1005: Subtask create_fact_table_conso_energy_region
[2024-03-10T21:10:52.399+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_fact_table_conso_energy_region manual__2024-03-10T21:03:03.293033+00:00 [running]> on host 952b3f8a1a94
[2024-03-10T21:10:52.655+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_fact_table_conso_energy_region' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T21:03:03.293033+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T21:03:03.293033+00:00'
[2024-03-10T21:10:55.256+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 401, in create_fact_table_conso_energy_region
    'code_categorie_consommation','code_naf'
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['id_operateur'] not in index"
[2024-03-10T21:10:55.315+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=EnergyWarehouse, task_id=create_fact_table_conso_energy_region, execution_date=20240310T210303, start_date=20240310T211051, end_date=20240310T211055
[2024-03-10T21:10:55.397+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1005 for task create_fact_table_conso_energy_region ("['id_operateur'] not in index"; 2995)
[2024-03-10T21:10:55.486+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-10T21:10:55.554+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
