[2023-06-15T11:39:23.252+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_university_api_send_psql.send_to_postgresql manual__2023-06-15T11:39:03.308504+00:00 [queued]>
[2023-06-15T11:39:23.275+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_university_api_send_psql.send_to_postgresql manual__2023-06-15T11:39:03.308504+00:00 [queued]>
[2023-06-15T11:39:23.277+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-15T11:39:23.305+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): send_to_postgresql> on 2023-06-15 11:39:03.308504+00:00
[2023-06-15T11:39:23.315+0000] {standard_task_runner.py:57} INFO - Started process 11652 to run task
[2023-06-15T11:39:23.327+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'get_university_api_send_psql', 'send_to_postgresql', 'manual__2023-06-15T11:39:03.308504+00:00', '--job-id', '1731', '--raw', '--subdir', 'DAGS_FOLDER/data-university-from-api-dag/data_university_from_api_dag.py', '--cfg-path', '/tmp/tmpmtrya8wx']
[2023-06-15T11:39:23.332+0000] {standard_task_runner.py:85} INFO - Job 1731: Subtask send_to_postgresql
[2023-06-15T11:39:23.417+0000] {task_command.py:410} INFO - Running <TaskInstance: get_university_api_send_psql.send_to_postgresql manual__2023-06-15T11:39:03.308504+00:00 [running]> on host cd01a659cc96
[2023-06-15T11:39:23.533+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_university_api_send_psql' AIRFLOW_CTX_TASK_ID='send_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T11:39:03.308504+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T11:39:03.308504+00:00'
[2023-06-15T11:39:24.564+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-university-from-api-dag/data_university_from_api_dag.py", line 141, in _send_to_postgresql
    """, (country, alpha_two_code, name, state_province, domains, web_pages))
psycopg2.errors.InvalidTextRepresentation: malformed array literal: "ieseg.fr"
LINE 3: ...'France', 'FR', 'IÉSEG School of Management', '', 'ieseg.fr'...
                                                             ^
DETAIL:  Array value must start with "{" or dimension information.

[2023-06-15T11:39:24.592+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=get_university_api_send_psql, task_id=send_to_postgresql, execution_date=20230615T113903, start_date=20230615T113923, end_date=20230615T113924
[2023-06-15T11:39:24.620+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1731 for task send_to_postgresql (malformed array literal: "ieseg.fr"
LINE 3: ...'France', 'FR', 'IÉSEG School of Management', '', 'ieseg.fr'...
                                                             ^
DETAIL:  Array value must start with "{" or dimension information.
; 11652)
[2023-06-15T11:39:24.674+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T11:39:24.716+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
