[2024-02-19T22:05:40.210+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_energy_data_and_transform._fetch_and_transform manual__2024-02-19T22:05:35.161442+00:00 [queued]>
[2024-02-19T22:05:40.246+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_energy_data_and_transform._fetch_and_transform manual__2024-02-19T22:05:35.161442+00:00 [queued]>
[2024-02-19T22:05:40.249+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-19T22:05:40.278+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): _fetch_and_transform> on 2024-02-19 22:05:35.161442+00:00
[2024-02-19T22:05:40.291+0000] {standard_task_runner.py:57} INFO - Started process 2199 to run task
[2024-02-19T22:05:40.300+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'extract_energy_data_and_transform', '_fetch_and_transform', 'manual__2024-02-19T22:05:35.161442+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/energy-prod-cons-dag/data_energy_dag.py', '--cfg-path', '/tmp/tmpwhl7935r']
[2024-02-19T22:05:40.306+0000] {standard_task_runner.py:85} INFO - Job 281: Subtask _fetch_and_transform
[2024-02-19T22:05:40.392+0000] {task_command.py:410} INFO - Running <TaskInstance: extract_energy_data_and_transform._fetch_and_transform manual__2024-02-19T22:05:35.161442+00:00 [running]> on host 952b3f8a1a94
[2024-02-19T22:05:40.521+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_energy_data_and_transform' AIRFLOW_CTX_TASK_ID='_fetch_and_transform' AIRFLOW_CTX_EXECUTION_DATE='2024-02-19T22:05:35.161442+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-19T22:05:35.161442+00:00'
[2024-02-19T22:05:40.528+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:198: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  return self.python_callable(*self.op_args, **self.op_kwargs)

[2024-02-19T22:06:05.478+0000] {logging_mixin.py:149} INFO - ******* STARTING columns ******  : Index(['operateur', 'annee', 'filiere', 'code_categorie_consommation',
       'libelle_categorie_consommation', 'code_grand_secteur',
       'libelle_grand_secteur', 'code_naf', 'libelle_secteur_naf2', 'conso',
       'pdl', 'indqual', 'nombre_mailles_secretisees', 'code_region',
       'libelle_region'],
      dtype='object')
[2024-02-19T22:06:05.512+0000] {logging_mixin.py:149} INFO - Strip leading and trailing whitespaces from column names
[2024-02-19T22:06:05.663+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/energy-prod-cons-dag/data_energy_dag.py", line 108, in _fetch_and_transform
    df_conso_energy_region = pd.read_csv(conso_energy_region_local, sep=';', error_bad_lines=False)
NameError: name 'conso_energy_region_local' is not defined
[2024-02-19T22:06:05.763+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=extract_energy_data_and_transform, task_id=_fetch_and_transform, execution_date=20240219T220535, start_date=20240219T220540, end_date=20240219T220605
[2024-02-19T22:06:05.969+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 281 for task _fetch_and_transform (name 'conso_energy_region_local' is not defined; 2199)
[2024-02-19T22:06:06.340+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-19T22:06:06.650+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
