[2024-02-27T11:09:37.916+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_fact_table_prod_energy manual__2024-02-27T11:03:29.076674+00:00 [queued]>
[2024-02-27T11:09:37.969+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_fact_table_prod_energy manual__2024-02-27T11:03:29.076674+00:00 [queued]>
[2024-02-27T11:09:37.972+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-02-27T11:09:38.016+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_fact_table_prod_energy> on 2024-02-27 11:03:29.076674+00:00
[2024-02-27T11:09:38.034+0000] {standard_task_runner.py:57} INFO - Started process 16678 to run task
[2024-02-27T11:09:38.052+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_fact_table_prod_energy', 'manual__2024-02-27T11:03:29.076674+00:00', '--job-id', '753', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmpzaqfmeiw']
[2024-02-27T11:09:38.060+0000] {standard_task_runner.py:85} INFO - Job 753: Subtask create_fact_table_prod_energy
[2024-02-27T11:09:38.225+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_fact_table_prod_energy manual__2024-02-27T11:03:29.076674+00:00 [running]> on host 952b3f8a1a94
[2024-02-27T11:09:38.534+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_fact_table_prod_energy' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T11:03:29.076674+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-27T11:03:29.076674+00:00'
[2024-02-27T11:09:38.727+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 320, in create_fact_table_prod_energy
    print('**** TYPE : ', df_prod_elect_dept.head(5) , '*********')
AttributeError: 'NoneType' object has no attribute 'head'
[2024-02-27T11:09:38.763+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=EnergyWarehouse, task_id=create_fact_table_prod_energy, execution_date=20240227T110329, start_date=20240227T110937, end_date=20240227T110938
[2024-02-27T11:09:38.791+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 753 for task create_fact_table_prod_energy ('NoneType' object has no attribute 'head'; 16678)
[2024-02-27T11:09:38.839+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-27T11:09:38.910+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
