[2024-02-06T14:37:47.720+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_energy_data_send_psql.read_local_csv_file manual__2024-02-06T14:37:37.108304+00:00 [queued]>
[2024-02-06T14:37:47.753+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_energy_data_send_psql.read_local_csv_file manual__2024-02-06T14:37:37.108304+00:00 [queued]>
[2024-02-06T14:37:47.756+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-06T14:37:47.786+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): read_local_csv_file> on 2024-02-06 14:37:37.108304+00:00
[2024-02-06T14:37:47.820+0000] {standard_task_runner.py:57} INFO - Started process 1458 to run task
[2024-02-06T14:37:47.840+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'get_energy_data_send_psql', 'read_local_csv_file', 'manual__2024-02-06T14:37:37.108304+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/energy-prod-cons-dag/data_energy_dag.py', '--cfg-path', '/tmp/tmpcm7vtyq4']
[2024-02-06T14:37:47.855+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask read_local_csv_file
[2024-02-06T14:37:47.996+0000] {task_command.py:410} INFO - Running <TaskInstance: get_energy_data_send_psql.read_local_csv_file manual__2024-02-06T14:37:37.108304+00:00 [running]> on host 952b3f8a1a94
[2024-02-06T14:37:48.135+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_energy_data_send_psql' AIRFLOW_CTX_TASK_ID='read_local_csv_file' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T14:37:37.108304+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T14:37:37.108304+00:00'
[2024-02-06T14:37:48.148+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/energy-prod-cons-dag/data_energy_dag.py", line 75, in _read_csv_file
    df_local_conso_energy_region = pd.read_csv(csv_file, sep=';')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 17, saw 2

[2024-02-06T14:37:48.169+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=get_energy_data_send_psql, task_id=read_local_csv_file, execution_date=20240206T143737, start_date=20240206T143747, end_date=20240206T143748
[2024-02-06T14:37:48.188+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 23 for task read_local_csv_file (Error tokenizing data. C error: Expected 1 fields in line 17, saw 2
; 1458)
[2024-02-06T14:37:48.242+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-06T14:37:48.275+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
