[2023-06-15T14:21:44.378+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_university_api_send_psql.send_to_postgresql manual__2023-06-15T14:20:24.094589+00:00 [queued]>
[2023-06-15T14:21:44.395+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_university_api_send_psql.send_to_postgresql manual__2023-06-15T14:20:24.094589+00:00 [queued]>
[2023-06-15T14:21:44.397+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-15T14:21:44.419+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): send_to_postgresql> on 2023-06-15 14:20:24.094589+00:00
[2023-06-15T14:21:44.429+0000] {standard_task_runner.py:57} INFO - Started process 913 to run task
[2023-06-15T14:21:44.436+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'get_university_api_send_psql', 'send_to_postgresql', 'manual__2023-06-15T14:20:24.094589+00:00', '--job-id', '1922', '--raw', '--subdir', 'DAGS_FOLDER/data-university-from-api-dag/data_university_from_api_dag.py', '--cfg-path', '/tmp/tmpnzlw10wn']
[2023-06-15T14:21:44.439+0000] {standard_task_runner.py:85} INFO - Job 1922: Subtask send_to_postgresql
[2023-06-15T14:21:44.512+0000] {task_command.py:410} INFO - Running <TaskInstance: get_university_api_send_psql.send_to_postgresql manual__2023-06-15T14:20:24.094589+00:00 [running]> on host cd01a659cc96
[2023-06-15T14:21:44.633+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_university_api_send_psql' AIRFLOW_CTX_TASK_ID='send_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T14:20:24.094589+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T14:20:24.094589+00:00'
[2023-06-15T14:21:45.563+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-university-from-api-dag/data_university_from_api_dag.py", line 148, in _send_to_postgresql
    """, (country, alpha_two_code, name, state_province, domains, web_pages))
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
LINE 3: ...'France', 'FR', 'IÉSEG School of Management', '', 'ieseg.fr'...
                                                             ^
DETAIL:  Token "ieseg" is invalid.
CONTEXT:  JSON data, line 1: ieseg...

[2023-06-15T14:21:45.590+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=get_university_api_send_psql, task_id=send_to_postgresql, execution_date=20230615T142024, start_date=20230615T142144, end_date=20230615T142145
[2023-06-15T14:21:45.621+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1922 for task send_to_postgresql (invalid input syntax for type json
LINE 3: ...'France', 'FR', 'IÉSEG School of Management', '', 'ieseg.fr'...
                                                             ^
DETAIL:  Token "ieseg" is invalid.
CONTEXT:  JSON data, line 1: ieseg...
; 913)
[2023-06-15T14:21:45.659+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T14:21:45.706+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
