[2023-06-14T20:52:01.202+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_university_api_send_psql.read_json_file manual__2023-06-14T20:51:27.561602+00:00 [queued]>
[2023-06-14T20:52:01.224+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_university_api_send_psql.read_json_file manual__2023-06-14T20:51:27.561602+00:00 [queued]>
[2023-06-14T20:52:01.226+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-14T20:52:01.252+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): read_json_file> on 2023-06-14 20:51:27.561602+00:00
[2023-06-14T20:52:01.263+0000] {standard_task_runner.py:57} INFO - Started process 10402 to run task
[2023-06-14T20:52:01.273+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'get_university_api_send_psql', 'read_json_file', 'manual__2023-06-14T20:51:27.561602+00:00', '--job-id', '1719', '--raw', '--subdir', 'DAGS_FOLDER/data-university-from-api-dag/data_university_from_api_dag.py', '--cfg-path', '/tmp/tmpueu8xnrz']
[2023-06-14T20:52:01.278+0000] {standard_task_runner.py:85} INFO - Job 1719: Subtask read_json_file
[2023-06-14T20:52:01.369+0000] {task_command.py:410} INFO - Running <TaskInstance: get_university_api_send_psql.read_json_file manual__2023-06-14T20:51:27.561602+00:00 [running]> on host cd01a659cc96
[2023-06-14T20:52:01.514+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_university_api_send_psql' AIRFLOW_CTX_TASK_ID='read_json_file' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T20:51:27.561602+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T20:51:27.561602+00:00'
[2023-06-14T20:52:01.561+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-university-from-api-dag/data_university_from_api_dag.py", line 83, in _read_json_file
    names = list(json_object.keys())
AttributeError: 'list' object has no attribute 'keys'
[2023-06-14T20:52:01.584+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=get_university_api_send_psql, task_id=read_json_file, execution_date=20230614T205127, start_date=20230614T205201, end_date=20230614T205201
[2023-06-14T20:52:01.608+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1719 for task read_json_file ('list' object has no attribute 'keys'; 10402)
[2023-06-14T20:52:01.649+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T20:52:01.695+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
