[2023-06-14T13:03:55.476+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_api_send_psql.send_to_postgresql manual__2023-06-14T13:03:31.986338+00:00 [queued]>
[2023-06-14T13:03:55.491+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_api_send_psql.send_to_postgresql manual__2023-06-14T13:03:31.986338+00:00 [queued]>
[2023-06-14T13:03:55.493+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-14T13:03:55.514+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): send_to_postgresql> on 2023-06-14 13:03:31.986338+00:00
[2023-06-14T13:03:55.523+0000] {standard_task_runner.py:57} INFO - Started process 2337 to run task
[2023-06-14T13:03:55.530+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'get_api_send_psql', 'send_to_postgresql', 'manual__2023-06-14T13:03:31.986338+00:00', '--job-id', '1494', '--raw', '--subdir', 'DAGS_FOLDER/end_to_end_pipeline_***.py', '--cfg-path', '/tmp/tmpeuuc7n8r']
[2023-06-14T13:03:55.534+0000] {standard_task_runner.py:85} INFO - Job 1494: Subtask send_to_postgresql
[2023-06-14T13:03:55.602+0000] {task_command.py:410} INFO - Running <TaskInstance: get_api_send_psql.send_to_postgresql manual__2023-06-14T13:03:31.986338+00:00 [running]> on host cd01a659cc96
[2023-06-14T13:03:55.703+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_api_send_psql' AIRFLOW_CTX_TASK_ID='send_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T13:03:31.986338+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T13:03:31.986338+00:00'
[2023-06-14T13:03:55.728+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/end_to_end_pipeline_airflow.py", line 65, in _send_to_postgresql
    host="localhost", port="5433")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-06-14T13:03:55.745+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=get_api_send_psql, task_id=send_to_postgresql, execution_date=20230614T130331, start_date=20230614T130355, end_date=20230614T130355
[2023-06-14T13:03:55.760+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1494 for task send_to_postgresql (connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 2337)
[2023-06-14T13:03:55.784+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T13:03:55.818+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
