[2024-03-10T20:30:22.013+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_secteur_naf scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-10T20:30:22.045+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_secteur_naf scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-10T20:30:22.051+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-03-10T20:30:22.096+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_dim_secteur_naf> on 2024-03-08 00:00:00+00:00
[2024-03-10T20:30:22.115+0000] {standard_task_runner.py:57} INFO - Started process 1753 to run task
[2024-03-10T20:30:22.137+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_dim_secteur_naf', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '892', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmpyfl2keir']
[2024-03-10T20:30:22.144+0000] {standard_task_runner.py:85} INFO - Job 892: Subtask create_dim_secteur_naf
[2024-03-10T20:30:22.324+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_dim_secteur_naf scheduled__2024-03-08T00:00:00+00:00 [running]> on host 952b3f8a1a94
[2024-03-10T20:30:23.314+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_dim_secteur_naf' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2024-03-10T20:30:23.425+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 268, in create_dim_secteur_naf
    secteur_naf_dim = df_conso_energy_region[['code_naf',  'libelle_secteur_naf2']].drop_duplicates().reset_index(drop=True)
TypeError: 'NoneType' object is not subscriptable
[2024-03-10T20:30:23.476+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=EnergyWarehouse, task_id=create_dim_secteur_naf, execution_date=20240308T000000, start_date=20240310T203022, end_date=20240310T203023
[2024-03-10T20:30:23.557+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 892 for task create_dim_secteur_naf ('NoneType' object is not subscriptable; 1753)
[2024-03-10T20:30:23.622+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-10T20:30:23.895+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
