[2024-02-26T22:46:26.458+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_department manual__2024-02-26T22:40:54.801491+00:00 [queued]>
[2024-02-26T22:46:26.542+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_department manual__2024-02-26T22:40:54.801491+00:00 [queued]>
[2024-02-26T22:46:26.544+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-02-26T22:46:26.753+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_dim_department> on 2024-02-26 22:40:54.801491+00:00
[2024-02-26T22:46:26.987+0000] {standard_task_runner.py:57} INFO - Started process 4985 to run task
[2024-02-26T22:46:27.067+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_dim_department', 'manual__2024-02-26T22:40:54.801491+00:00', '--job-id', '538', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmphfd6jew8']
[2024-02-26T22:46:27.086+0000] {standard_task_runner.py:85} INFO - Job 538: Subtask create_dim_department
[2024-02-26T22:46:27.444+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_dim_department manual__2024-02-26T22:40:54.801491+00:00 [running]> on host 952b3f8a1a94
[2024-02-26T22:46:28.555+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_dim_department' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T22:40:54.801491+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T22:40:54.801491+00:00'
[2024-02-26T22:46:28.597+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:198: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  return self.python_callable(*self.op_args, **self.op_kwargs)

[2024-02-26T22:46:29.064+0000] {logging_mixin.py:149} INFO - ****DISPLAY HEAD :   operateur,annee,filiere,consoa,pdla,indquala,consoi,pdli,indquali,consot,pdlt,indqualt,consor,pdlr,indqualr,consona,pdlna,indqualna,code_departement,libelle_departement,code_region,libelle_region,id_filiere,consototale
0  Enedis,2011,Electricité,26490.69,334,0.957,838...                                                                                                                                                                        
1  Enedis,2011,Electricité,25747.9,373,0.976,4263...                                                                                                                                                                        
2  Enedis,2011,Electricité,13601.05,118,0.946,105...                                                                                                                                                                        
3  Enedis,2011,Electricité,6611.47,62,0.949,44404...                                                                                                                                                                        
4  Enedis,2011,Electricité,33909.59,288,0.944,524...                                                                                                                                                                        
[2024-02-26T22:46:29.071+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 192, in create_dim_department
    departement_dim = df_conso_energy_dept[['code_departement' , 'libelle_departement' , 'code_region']].drop_duplicates().reset_index(drop=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['code_departement', 'libelle_departement', 'code_region'], dtype='object')] are in the [columns]"
[2024-02-26T22:46:29.157+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=EnergyWarehouse, task_id=create_dim_department, execution_date=20240226T224054, start_date=20240226T224626, end_date=20240226T224629
[2024-02-26T22:46:29.241+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 538 for task create_dim_department ("None of [Index(['code_departement', 'libelle_departement', 'code_region'], dtype='object')] are in the [columns]"; 4985)
[2024-02-26T22:46:29.337+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-26T22:46:29.602+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
