[2024-02-27T11:02:49.316+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_fact_table_prod_energy manual__2024-02-27T11:02:07.993140+00:00 [queued]>
[2024-02-27T11:02:49.347+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_fact_table_prod_energy manual__2024-02-27T11:02:07.993140+00:00 [queued]>
[2024-02-27T11:02:49.350+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-02-27T11:02:49.396+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_fact_table_prod_energy> on 2024-02-27 11:02:07.993140+00:00
[2024-02-27T11:02:49.422+0000] {standard_task_runner.py:57} INFO - Started process 16402 to run task
[2024-02-27T11:02:49.445+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_fact_table_prod_energy', 'manual__2024-02-27T11:02:07.993140+00:00', '--job-id', '728', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmpzrmq2auq']
[2024-02-27T11:02:49.451+0000] {standard_task_runner.py:85} INFO - Job 728: Subtask create_fact_table_prod_energy
[2024-02-27T11:02:49.650+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_fact_table_prod_energy manual__2024-02-27T11:02:07.993140+00:00 [running]> on host 952b3f8a1a94
[2024-02-27T11:02:49.900+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_fact_table_prod_energy' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T11:02:07.993140+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-27T11:02:07.993140+00:00'
[2024-02-27T11:02:50.144+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 320, in create_fact_table_prod_energy
    print('**** TYPE : ', df_prod_elect_dept.head(5) , '*********')
AttributeError: 'NoneType' object has no attribute 'head'
[2024-02-27T11:02:50.188+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=EnergyWarehouse, task_id=create_fact_table_prod_energy, execution_date=20240227T110207, start_date=20240227T110249, end_date=20240227T110250
[2024-02-27T11:02:50.225+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 728 for task create_fact_table_prod_energy ('NoneType' object has no attribute 'head'; 16402)
[2024-02-27T11:02:50.305+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-27T11:02:50.414+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
