[2024-03-10T20:30:49.852+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_grand_secteur scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-10T20:30:49.896+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_grand_secteur scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-10T20:30:49.899+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-03-10T20:30:49.933+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_dim_grand_secteur> on 2024-03-08 00:00:00+00:00
[2024-03-10T20:30:49.949+0000] {standard_task_runner.py:57} INFO - Started process 1769 to run task
[2024-03-10T20:30:49.966+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_dim_grand_secteur', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '896', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmp36y1_5b8']
[2024-03-10T20:30:49.972+0000] {standard_task_runner.py:85} INFO - Job 896: Subtask create_dim_grand_secteur
[2024-03-10T20:30:50.122+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_dim_grand_secteur scheduled__2024-03-08T00:00:00+00:00 [running]> on host 952b3f8a1a94
[2024-03-10T20:30:50.360+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_dim_grand_secteur' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2024-03-10T20:30:50.393+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 283, in create_dim_grand_secteur
    grand_secteur_dim = df_conso_energy_region[['code_grand_secteur',  'libelle_grand_secteur']].drop_duplicates().reset_index(drop=True)
TypeError: 'NoneType' object is not subscriptable
[2024-03-10T20:30:50.421+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=EnergyWarehouse, task_id=create_dim_grand_secteur, execution_date=20240308T000000, start_date=20240310T203049, end_date=20240310T203050
[2024-03-10T20:30:50.449+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 896 for task create_dim_grand_secteur ('NoneType' object is not subscriptable; 1769)
[2024-03-10T20:30:50.498+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-10T20:30:50.610+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
