[2024-03-11T13:49:54.923+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.send_csv_s3 manual__2024-03-11T13:40:41.625064+00:00 [queued]>
[2024-03-11T13:49:54.953+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.send_csv_s3 manual__2024-03-11T13:40:41.625064+00:00 [queued]>
[2024-03-11T13:49:54.956+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-03-11T13:49:54.980+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): send_csv_s3> on 2024-03-11 13:40:41.625064+00:00
[2024-03-11T13:49:54.995+0000] {standard_task_runner.py:57} INFO - Started process 4287 to run task
[2024-03-11T13:49:55.011+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'send_csv_s3', 'manual__2024-03-11T13:40:41.625064+00:00', '--job-id', '1322', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmpz6937ijx']
[2024-03-11T13:49:55.019+0000] {standard_task_runner.py:85} INFO - Job 1322: Subtask send_csv_s3
[2024-03-11T13:49:55.123+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.send_csv_s3 manual__2024-03-11T13:40:41.625064+00:00 [running]> on host 952b3f8a1a94
[2024-03-11T13:49:55.261+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='send_csv_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T13:40:41.625064+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-11T13:40:41.625064+00:00'
[2024-03-11T13:49:55.268+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 515, in _send_csv_s3
    configurations = json.load(output)
NameError: name 'json' is not defined
[2024-03-11T13:49:55.285+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=EnergyWarehouse, task_id=send_csv_s3, execution_date=20240311T134041, start_date=20240311T134954, end_date=20240311T134955
[2024-03-11T13:49:55.304+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1322 for task send_csv_s3 (name 'json' is not defined; 4287)
[2024-03-11T13:49:55.351+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-11T13:49:55.391+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
