[2024-02-27T10:40:51.178+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_operateur manual__2024-02-27T10:40:07.240232+00:00 [queued]>
[2024-02-27T10:40:51.223+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_operateur manual__2024-02-27T10:40:07.240232+00:00 [queued]>
[2024-02-27T10:40:51.226+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-02-27T10:40:51.402+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_dim_operateur> on 2024-02-27 10:40:07.240232+00:00
[2024-02-27T10:40:51.541+0000] {standard_task_runner.py:57} INFO - Started process 15603 to run task
[2024-02-27T10:40:51.568+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_dim_operateur', 'manual__2024-02-27T10:40:07.240232+00:00', '--job-id', '660', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmpv9d4ubi9']
[2024-02-27T10:40:51.581+0000] {standard_task_runner.py:85} INFO - Job 660: Subtask create_dim_operateur
[2024-02-27T10:40:51.923+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_dim_operateur manual__2024-02-27T10:40:07.240232+00:00 [running]> on host 952b3f8a1a94
[2024-02-27T10:40:52.207+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_dim_operateur' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T10:40:07.240232+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-27T10:40:07.240232+00:00'
[2024-02-27T10:40:52.225+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 189, in create_dim_operateur
    df_conso_energy_region = kwargs['task_instance'].xcom_pull(task_ids='load_conso_energy_region', key='df_conso_energy_region')
NameError: name 'kwargs' is not defined
[2024-02-27T10:40:52.271+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=EnergyWarehouse, task_id=create_dim_operateur, execution_date=20240227T104007, start_date=20240227T104051, end_date=20240227T104052
[2024-02-27T10:40:52.343+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 660 for task create_dim_operateur (name 'kwargs' is not defined; 15603)
[2024-02-27T10:40:52.382+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-27T10:40:52.514+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
