[2024-01-30T15:16:55.137+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_s3_csv_files.fetch_csv_files_task manual__2024-01-30T15:16:47.511104+00:00 [queued]>
[2024-01-30T15:16:55.163+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_s3_csv_files.fetch_csv_files_task manual__2024-01-30T15:16:47.511104+00:00 [queued]>
[2024-01-30T15:16:55.168+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-01-30T15:16:55.193+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fetch_csv_files_task> on 2024-01-30 15:16:47.511104+00:00
[2024-01-30T15:16:55.205+0000] {standard_task_runner.py:57} INFO - Started process 2121 to run task
[2024-01-30T15:16:55.225+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_s3_csv_files', 'fetch_csv_files_task', 'manual__2024-01-30T15:16:47.511104+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/energy-prod-cons-dag/data_energy_dag.py', '--cfg-path', '/tmp/tmp1fbir81_']
[2024-01-30T15:16:55.237+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask fetch_csv_files_task
[2024-01-30T15:16:55.673+0000] {task_command.py:410} INFO - Running <TaskInstance: fetch_s3_csv_files.fetch_csv_files_task manual__2024-01-30T15:16:47.511104+00:00 [running]> on host 952b3f8a1a94
[2024-01-30T15:16:56.312+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_s3_csv_files' AIRFLOW_CTX_TASK_ID='fetch_csv_files_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T15:16:47.511104+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T15:16:47.511104+00:00'
[2024-01-30T15:16:56.355+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/energy-prod-cons-dag/data_energy_dag.py", line 49, in _fetch_csv_files
    s3_hook = S3Hook(aws_conn_id=s3_conn_id, region_name=region_name)
NameError: name 'S3Hook' is not defined
[2024-01-30T15:16:56.424+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=fetch_s3_csv_files, task_id=fetch_csv_files_task, execution_date=20240130T151647, start_date=20240130T151655, end_date=20240130T151656
[2024-01-30T15:16:56.471+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 6 for task fetch_csv_files_task (name 'S3Hook' is not defined; 2121)
[2024-01-30T15:16:56.518+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-01-30T15:16:56.568+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
